name: $name
version: $version
main: net.uniquepixels.lobbysystem.LobbySystem
description: $description
depend: [ PaperCore ]
author: DasShorty, KaiBlack
api-version: "$apiVersion"

commands:
  build:
    permission: lobbysystem.build_mode
  setup:
    permission: lobbysystem.setup
